[package]
name = "mage"
version = "0.1.0"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]

[lib]
name = "mage"
#crate-type = ["lib", "dylib", "rlib", "cdylib", "staticlib"]
crate-type = ["lib", "cdylib", "staticlib"]
path = "src/lib.rs"

[dependencies]
custom_error = "*"
sodiumoxide = "*"
crossbeam-channel = "*"
lazy_static = "*"
