[package]
name = "mage"
version = "0.1.0"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]

[lib]
name = "mage"
crate-type = ["lib", "cdylib", "staticlib"]
path = "src/lib.rs"

[dependencies]
#std = {default-features=false, features=["panic_immediate_abort"]}
bufstream = "*"
custom_error = "*"
sodiumoxide = "*"

[build-dependencies]
cbindgen = "*"

[features]
default = [ "ffi" ]

ffi = []

[profile.release]
# For these check https://github.com/johnthagen/min-sized-rust
lto = true
codegen-units = 1
