extern crate bufstream;
extern crate sodiumoxide;

mod packet;
mod stream;
pub mod channel;
pub mod connection;
pub mod transport;

#[cfg(not(test))]
mod settings; // Generated by build.rs

#[cfg(feature = "ffi")]
pub mod api_ffi;

#[cfg(feature = "tool")]
pub mod tool;

#[macro_export]
macro_rules! error_str {
    ($fmt: expr, $($name: ident), *) => { error_str!(format!($fmt, $($name = $name),*)) };
    ($fmt: expr) => { Error::new(ErrorKind::Other, $fmt) }
}
