name: Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/})
    - name: Setup Dependencies
      run: cargo install cargo-tarpaulin
    - name: Check Coverage
      run: cargo tarpaulin -v --coveralls ${{ secrets.COVERALLS_TOKEN }} -b ${BRANCH}
