name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin ${GITHUB_REF}
      - name: Setup Dependencies
        run: cargo install -f cargo-tarpaulin
      - name: Test Project on ${{ matrix.os }}
        run: cargo test -v
      - name: Generate Coverage report
        if: runner.os == "Linux"
        run: cargo tarpaulin -v -b --coveralls ${{ secrets.COVERALLS_TOKEN }}
